version: '3'

services: 
    api:
        build: 
            context: ./
            dockerfile: ./Dockerfile
        links: 
            - postgres
        ports: 
            - 8080:8080
        depends_on: 
            - postgres
        restart: always
    postgres:
        build:
            context: ./
            dockerfile: Dockerfile-psql
        restart: always
        volumes: 
            - ./postgres-volume:/var/lib/postgresql/data


