FROM golang:1-alpine AS build

COPY go.mod go.sum /app/
WORKDIR /app
RUN go mod download

COPY . /app
RUN apk add --no-cache libc6-compat curl
RUN curl -sL https://taskfile.dev/install.sh | sh
ENTRYPOINT ["bin/task"]
CMD ["-w", "dev"]