version: '2'

tasks:
  build:
    sources:
      - server.go
      - '**/*.go'
    cmds:
      - go build -o bin/server
   
  dev:
    deps:
      - build
    env:
      APP_ENV: dev
    cmds:
      - tmp/server

  default:
    deps:
      - build

