version: '2'

tasks:
  build:
    sources:
      - server.go
      - '**/*.go'
    cmds:
      - go build -o tmp/server
  dev:
    deps:
      - build
    env:
      APP_ENV: dev
    cmds:
      - tmp/server
  bootstrap:
    cmds:
      - sudo -u postgres createdb komfy
      - psql -f sql_files/create_db.sql komfy komfy
      - psql -f sql_files/populate_db.sql

  default:
    deps:
      - build
