DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS entities CASCADE;
DROP TYPE IF EXISTS CONTENT_TYPE;
DROP TYPE IF EXISTS ENTITY_TYPE;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS contain;
DROP TABLE IF EXISTS assets CASCADE;
DROP TYPE IF EXISTS RESSOURCE_TYPE;
